import type { Puzzle } from '@/types/game';

export const PUZZLES: Puzzle[] = [
  {
    id: 'p1',
    name: 'First Shelter',
    description: 'Create a House to survive the night.',
    targetElementId: 'house',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 6,
    hints: ['You need bricks first', 'Bricks come from mud and fire', 'Mud is earth + water'],
    difficulty: 'easy',
    packId: 'classical',
  },
  {
    id: 'p2',
    name: 'Wheeled Travel',
    description: 'Build a Car to explore the world.',
    targetElementId: 'car',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 8,
    hints: ['You need a cart', 'A cart needs wheels', 'Wheels need wood and tools'],
    difficulty: 'medium',
    packId: 'classical',
  },
  {
    id: 'p3',
    name: 'Sky Voyager',
    description: 'Create an Airplane to touch the clouds.',
    targetElementId: 'airplane',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 10,
    hints: ['You need a car first', 'Then add air to a car'],
    difficulty: 'hard',
    packId: 'classical',
  },
  {
    id: 'p4',
    name: 'Green Thumb',
    description: 'Grow a Flower from a tiny seed.',
    targetElementId: 'flower',
    startingElements: ['seed', 'spore', 'soil', 'light'],
    maxSteps: 5,
    hints: ['Seeds need soil', 'Plants need light', 'Flowers bloom from plants'],
    difficulty: 'easy',
    packId: 'vital',
  },
  {
    id: 'p5',
    name: 'Cosmic Wonder',
    description: 'Paint a Rainbow across the sky.',
    targetElementId: 'rainbow',
    startingElements: ['star', 'void', 'sun', 'moon'],
    maxSteps: 6,
    hints: ['You need water in the sky', 'Rain comes from water + air', 'Sun + rain = rainbow'],
    difficulty: 'medium',
    packId: 'celestial',
  },
  {
    id: 'p6',
    name: 'Deep Blue',
    description: 'Create the vast Ocean.',
    targetElementId: 'ocean',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 7,
    hints: ['Start with rain', 'Rain + earth = plant', 'Keep adding water to grow'],
    difficulty: 'medium',
    packId: 'classical',
  },
  {
    id: 'p7',
    name: 'Forest Guardian',
    description: 'Grow a mighty Forest.',
    targetElementId: 'forest',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 6,
    hints: ['You need trees first', 'Trees grow from grass + sun', 'Grass comes from plant + earth'],
    difficulty: 'medium',
    packId: 'classical',
  },
  {
    id: 'p8',
    name: 'Time Keeper',
    description: 'Craft a Clock to measure time.',
    targetElementId: 'clock',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 7,
    hints: ['You need tools', 'Tools need metal and wood', 'Clocks need tools and sun'],
    difficulty: 'medium',
    packId: 'classical',
  },
  {
    id: 'p9',
    name: 'Glass Maker',
    description: 'Forge transparent Glass from sand.',
    targetElementId: 'glass',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 5,
    hints: ['You need sand', 'Sand comes from stone + air', 'Stone comes from lava + water'],
    difficulty: 'easy',
    packId: 'classical',
  },
  {
    id: 'p10',
    name: 'Star Forge',
    description: 'Weave a Galaxy from the stars.',
    targetElementId: 'galaxy',
    startingElements: ['star', 'void', 'sun', 'moon'],
    maxSteps: 6,
    hints: ['Combine two stars', 'That is all you need'],
    difficulty: 'easy',
    packId: 'celestial',
  },
  {
    id: 'p11',
    name: 'Master Builder',
    description: 'Raise a Wall to protect your home.',
    targetElementId: 'wall',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 5,
    hints: ['You need bricks', 'Two bricks make a wall'],
    difficulty: 'easy',
    packId: 'classical',
  },
  {
    id: 'p12',
    name: 'Lightning Rod',
    description: 'Capture Lightning from the sky.',
    targetElementId: 'lightning',
    startingElements: ['fire', 'water', 'earth', 'air'],
    maxSteps: 6,
    hints: ['You need energy', 'Energy comes from fire + air', 'Energy + air = lightning'],
    difficulty: 'medium',
    packId: 'classical',
  },
];